spring.application.name=springbootcrud
#spring.datasource.url=jdbc:mysql://localhost:3306/db_jpa_crud
spring.datasource.url=jdbc:mysql://db-jpa-crud.cros8qg6k68d.us-east-2.rds.amazonaws.com:3306/db_jpa_crud
spring.datasource.username=root
spring.datasource.password=${MYSQLP}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

#se desactiva la validacion automatica de hibernate
spring.jpa.properties.jakarta.persistence.validation.mode=none

